"""Adama (አዳማ) local businesses for demo seeding — bilingual descriptions."""

from __future__ import annotations

from werefa.shared.enums import VerificationStatus

ADAMA_SERVICES: dict[str, list[tuple[str, int, str, str]]] = {}
ADAMA_META: dict[str, dict[str, object]] = {}


def _desc(am: str, en: str) -> str:
    return f"{am.strip()}\n\n{en.strip()}"


def _entry(
    slug: str,
    biz_name: str,
    amharic_name: str,
    category: str,
    description_en: str,
    description_am: str,
    lat: float,
    lng: float,
    image_url: str,
    is_open: bool,
    rating: float,
    queue_length: int,
    services: list[tuple[str, int, float, str]],
    owner_index: int,
    address: str,
) -> tuple[str, str, str, str, float, float, str, int]:
    ADAMA_META[slug] = {
        "rating": rating,
        "queue_length": queue_length,
        "is_open": is_open,
        "amharic_name": amharic_name,
        "description": _desc(description_am, description_en),
        "category": category,
        "address": address,
        "image_url": image_url,
    }
    ADAMA_SERVICES[slug] = [
        (name, mins, f"{price:.2f}", desc) for name, mins, price, desc in services
    ]
    return (
        slug,
        biz_name,
        "Adama",
        "Oromia",
        lat,
        lng,
        VerificationStatus.verified.value,
        owner_index,
    )


ADAMA_LOCAL_ROWS: list[tuple[str, str, str, str, float, float, str, int]] = [
    _entry(
        "top-style-mens-barber",
        "Top Style Men's Barber",
        "ቶፕ ስታይል የፀጉር ቤት",
        "barbershop",
        "Modern men's grooming, haircuts, and beard trims in the heart of Adama.",
        "በአዳማ ከተማ የሚገኝ ዘመናዊ የፀጉር አስተካካይ።",
        8.5452,
        39.2681,
        "https://placehold.co/600x400/F472B6/FFFFFF.png?text=Top+Style+Barber",
        True,
        4.8,
        3,
        [
            ("Standard Haircut", 30, 150.00, "የመደበኛ ሸፍ ቆራጭ።"),
            ("Beard Trim & Shape", 15, 80.00, "የጺም ቆራጭ እና ቅርጽ።"),
        ],
        13,
        "Adama, Kebele 03",
    ),
    _entry(
        "adama-kebele-04-office",
        "Adama Kebele 04 Administrative Office",
        "አዳማ ከተማ ቀበሌ 04 አስተዳደር ጽ/ቤት",
        "government",
        "Local administrative office for resident ID cards, civil status registration, and clearance letters.",
        "የቀበሌ 04 ነዋሪዎች መታወቂያ እና አስተዳደራዊ አገልግሎቶች።",
        8.5398,
        39.2745,
        "https://placehold.co/600x400/3B82F6/FFFFFF.png?text=Kebele+04",
        True,
        3.5,
        18,
        [
            ("New Resident ID", 25, 50.00, "አዲስ የመኖሪያ ቤት መታወቂያ።"),
            ("Document Authentication", 15, 20.00, "ሰነድ ማረጋገጥ።"),
        ],
        14,
        "Adama, Kebele 04",
    ),
    _entry(
        "abdi-medium-clinic",
        "Abdi Medium Clinic",
        "አብዲ መካከለኛ ክሊኒክ",
        "clinic",
        "Affordable outpatient health services, general consultation, and laboratory testing.",
        "የተሟላ የህክምና አገልግሎት የሚሰጥ መካከለኛ ክሊኒክ።",
        8.5489,
        39.2710,
        "https://placehold.co/600x400/10B981/FFFFFF.png?text=Abdi+Clinic",
        True,
        4.2,
        6,
        [
            ("General Doctor Consultation", 20, 300.00, "አጠቃላይ ዶክተር ምክር።"),
            ("Blood/Lab Test", 10, 250.00, "የደም እና ላብራቶሪ ምርመራ።"),
        ],
        15,
        "Adama, Bole area",
    ),
    _entry(
        "cbe-aba-geda",
        "Commercial Bank of Ethiopia (Aba Geda)",
        "የኢትዮጵያ ንግድ ባንክ (አባ ገዳ)",
        "bank",
        "Main branch services including account opening, large withdrawals, and international transfers.",
        "ፈጣን እና አስተማማኝ የባንክ አገልግሎት።",
        8.5411,
        39.2655,
        "https://placehold.co/600x400/8B5CF6/FFFFFF.png?text=CBE+Aba+Geda",
        True,
        4.0,
        24,
        [
            ("Customer Service", 15, 0.00, "የደንበኞች አገልግሎት።"),
            ("Teller / Cash Deposit", 5, 0.00, "ገንዘብ መቀበል እና መክፈል።"),
        ],
        1,
        "Adama, Aba Geda",
    ),
    _entry(
        "konjo-womens-salon",
        "Konjo Women's Beauty Salon",
        "ቆንጆ የሴቶች የውበት ሳሎን",
        "salon",
        "Premium hair styling, braiding, manicures, and bridal makeup services.",
        "ለሴቶች የተሟላ የውበት አጠባበቅ አገልግሎት።",
        8.5520,
        39.2632,
        "https://placehold.co/600x400/F472B6/FFFFFF.png?text=Konjo+Salon",
        True,
        4.9,
        4,
        [
            ("Hair Braiding (Shuruba)", 90, 400.00, "ሹሩባ / የፀጉር ስፌት።"),
            ("Manicure & Pedicure", 45, 350.00, "የእጅ እና የእግር ስፌት።"),
        ],
        2,
        "Adama, central market",
    ),
    _entry(
        "adama-woreda-revenue",
        "Adama Woreda Revenue Authority",
        "አዳማ ወረዳ ገቢዎች ባለስልጣን",
        "government",
        "Tax collection, business license renewal, and TIN registration for SMEs.",
        "የግብር አከፋፈል እና ንግድ ፈቃድ አገልግሎቶች።",
        8.5365,
        39.2780,
        "https://placehold.co/600x400/3B82F6/FFFFFF.png?text=Revenue+Office",
        True,
        3.2,
        32,
        [
            ("Business License Renewal", 40, 100.00, "የንግድ ፈቃድ እድሳት።"),
            ("Annual Tax Payment", 20, 0.00, "ዓመታዊ ግብር ክፍያ።"),
        ],
        3,
        "Adama, Woreda office",
    ),
    _entry(
        "smile-dental-clinic",
        "Smile Dental Clinic",
        "ስማይል የጥርስ ህክምና",
        "dental",
        "Advanced dental care, tooth extraction, cleaning, and braces adjustment.",
        "ዘመናዊ የጥርስ ህክምና እና ማፅዳት አገልግሎት።",
        8.5471,
        39.2810,
        "https://placehold.co/600x400/10B981/FFFFFF.png?text=Smile+Dental",
        False,
        4.6,
        0,
        [
            ("Dental Checkup & Cleaning", 45, 800.00, "የጥርስ ምርመራ እና ማጽዳት።"),
            ("Tooth Extraction", 60, 1200.00, "የጥርስ ማስወገድ።"),
        ],
        4,
        "Adama, Megala",
    ),
    _entry(
        "adama-express-auto-garage",
        "Adama Express Auto Garage",
        "አዳማ ኤክስፕረስ መኪና ጥገና",
        "auto",
        "Fast and reliable mechanic services, oil changes, and computerized diagnostics.",
        "የመኪና ጥገና እና የሞተር እጥበት።",
        8.5312,
        39.2605,
        "https://placehold.co/600x400/4B5563/FFFFFF.png?text=Express+Garage",
        True,
        4.4,
        5,
        [
            ("Full Synthetic Oil Change", 30, 2500.00, "ሙሉ የቅባት ለውጥ።"),
            ("Computerized Diagnostic", 40, 500.00, "የኮምፒውተር ዳያግኖስቲክ።"),
        ],
        5,
        "Adama, industrial area",
    ),
    _entry(
        "ethio-vet-clinic",
        "Ethio-Vet Animal Clinic",
        "ኢትዮ-ቬት የእንስሳት ክሊኒክ",
        "clinic",
        "Veterinary services for pets and livestock, including vaccinations and surgery.",
        "የቤት እንስሳት ህክምና እና ክትባት።",
        8.5550,
        39.2766,
        "https://placehold.co/600x400/10B981/FFFFFF.png?text=Ethio-Vet",
        True,
        4.7,
        2,
        [
            ("Rabies Vaccination", 15, 300.00, "የቀበሮ በሽታ ክትባት።"),
            ("General Checkup", 25, 200.00, "አጠቃላይ የእንስሳት ምርመራ።"),
        ],
        6,
        "Adama, ASTU area",
    ),
    _entry(
        "adama-immigration-office",
        "Adama Immigration Office",
        "አዳማ ኢሚግሬሽን ጽ/ቤት",
        "government",
        "New passport issuance, renewals, and travel document authentication.",
        "የፓስፖርት እድሳት እና አዲስ ፓስፖርት ማውጣት።",
        8.5495,
        39.2690,
        "https://placehold.co/600x400/3B82F6/FFFFFF.png?text=Immigration",
        True,
        2.5,
        45,
        [
            ("Data Capture / Fingerprint", 15, 0.00, "ዳታ መመዝገብ / የጣት አሻራ።"),
            ("Passport Collection", 5, 0.00, "ፓስፖርት መሰብሰብ።"),
        ],
        7,
        "Adama, federal compound",
    ),
    _entry(
        "relax-spa-massage",
        "Relax Spa & Massage",
        "ሪላክስ ስፓ እና ማሳጅ",
        "fitness",
        "Therapeutic massages, sauna, and steam bath services for ultimate relaxation.",
        "የማሳጅ እና ሳውና አገልግሎት።",
        8.5422,
        39.2789,
        "https://placehold.co/600x400/F472B6/FFFFFF.png?text=Relax+Spa",
        True,
        4.8,
        1,
        [
            ("Full Body Swedish Massage", 60, 1000.00, "ሙሉ ሰውነት ማሳጅ።"),
            ("Steam & Sauna Access", 45, 400.00, "ሳውና እና ትንፋሽ ክፍል።"),
        ],
        8,
        "Adama, leisure district",
    ),
    _entry(
        "fikre-photography-studio",
        "Fikre Photography Studio",
        "ፍቅሬ ፎቶግራፊ",
        "other",
        "Professional studio portraits, passport-sized photos, and family shoots.",
        "የፓስፖርት እና የሰርግ ፎቶግራፍ አገልግሎት።",
        8.5460,
        39.2644,
        "https://placehold.co/600x400/4B5563/FFFFFF.png?text=Fikre+Studio",
        True,
        4.5,
        4,
        [
            ("Instant Passport Photos (8x)", 10, 100.00, "ፈጣን የፓስፖርት ፎቶ (8 ቁጥር)።"),
            ("Studio Portrait Session", 30, 500.00, "የስቱዲዮ ፎቶ ቀን።"),
        ],
        9,
        "Adama, main road",
    ),
    _entry(
        "biftu-pharmacy",
        "Biftu Pharmacy",
        "ቢፍቱ ፋርማሲ",
        "pharmacy",
        "Prescription fulfillment, over-the-counter medicine, and medical supplies.",
        "የተለያዩ መድሀኒቶች እና የህክምና መገልገያዎች አቅራቢ።",
        8.5482,
        39.2705,
        "https://placehold.co/600x400/10B981/FFFFFF.png?text=Biftu+Pharmacy",
        True,
        4.3,
        8,
        [
            ("Prescription Pickup", 5, 0.00, "የሐኪም ወጥ መድሃኒት መውሰድ።"),
            ("Pharmacist Consultation", 10, 0.00, "የፋርማሲስት ምክር።"),
        ],
        10,
        "Adama, hospital road",
    ),
    _entry(
        "birhan-eye-care",
        "Birhan Eye Care",
        "ብርሃን የአይን ህክምና",
        "clinic",
        "Comprehensive eye exams, reading glasses, and contact lens fittings.",
        "የአይን ምርመራ እና የመነፅር ሽያጭ።",
        8.5435,
        39.2750,
        "https://placehold.co/600x400/10B981/FFFFFF.png?text=Birhan+Eye",
        True,
        4.6,
        3,
        [
            ("Computerized Eye Test", 20, 200.00, "የአይን ኮምፒውተር ምርመራ።"),
            ("Frame Fitting", 15, 0.00, "የመነፅር ማስተካከል።"),
        ],
        11,
        "Adama, Megenagna",
    ),
    _entry(
        "ethio-telecom-astu-branch",
        "Ethio Telecom (ASTU Branch)",
        "ኢትዮ ቴሌኮም (አዳማ ዩኒቨርሲቲ ቅርንጫፍ)",
        "telecom",
        "SIM card replacement, Telebirr registration, and broadband internet support.",
        "የሲም ካርድ ሽያጭ እና የቴሌብር አገልግሎት።",
        8.5580,
        39.2885,
        "https://placehold.co/600x400/3B82F6/FFFFFF.png?text=Ethio+Telecom",
        True,
        3.8,
        14,
        [
            ("SIM Replacement", 15, 50.00, "ሲም ካርድ መተካት።"),
            ("Telebirr Account Upgrade", 10, 0.00, "ቴሌብር መለያ ማሻሻል።"),
        ],
        12,
        "Adama, near ASTU",
    ),
]


def build_adama_biz_profiles() -> dict[str, dict[str, object]]:
    profiles: dict[str, dict[str, object]] = {}
    for slug, meta in ADAMA_META.items():
        profiles[slug] = {
            "category": meta["category"],
            "description": meta["description"],
            "address": meta.get("address", "Adama"),
            "show_phone_public": True,
            "phone": "+251221550000",
            "image_url": meta["image_url"],
            "is_open": meta["is_open"],
        }
    return profiles
